services:
  postgres:
    image: postgres:15
    container_name: postgres-saas
    environment:
      POSTGRES_DB: saas_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - saas-network
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-saas
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - saas-network
    
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=saas_auth
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=my-very-secret-jwt-key-you-will-never-guess
    networks:
      - saas-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - saas-network

volumes:
  postgres_data:

networks:
  saas-network:
    driver: bridge 